name: Publish extension to Visual Studio Marketplace
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Publish extension to Visual Studio Marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 19
      
      - name: "Install dependencies"
        run: npm install

      - name: "Install VSCE tool"
        run: npm install -g @vscode/vsce

      - name: Build VSIX package
        run: vsce package

      - name: Publish to marketplace
        if: startsWith(github.ref, 'refs/tags/')
        run: vsce publish ${{ github.ref }} --no-git-tag-version --pat "${{ secrets.MARKETPLACE_PAT }}"
        
      